provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  profile-fn:
    lang: dockerfile
    handler: ./generated/fn
    image: __FUNCTION_IMAGE__
    environment:
      write_debug: "true"
      ARTIFACT_KEY: "__ARTIFACT_KEY__"
      REDIS_HOST: "redis.jit-system.svc.cluster.local"
      REDIS_PORT: "6379"
      PROFILE_PATH: "/profiles/latest.mdox"
      PROFILE_DUMP_PATH: "/profiles/out.mdox"
      PORT: "8080"
